package com.client.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-08-23T20:36:44.813-05:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://interfaces.server.com/", name = "SongLibraryInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface SongLibraryInterface {

    @WebMethod
    @RequestWrapper(localName = "searchByGenre", targetNamespace = "http://interfaces.server.com/", className = "com.client.proxy.SearchByGenre")
    @ResponseWrapper(localName = "searchByGenreResponse", targetNamespace = "http://interfaces.server.com/", className = "com.client.proxy.SearchByGenreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.client.proxy.Song> searchByGenre(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchByTitle", targetNamespace = "http://interfaces.server.com/", className = "com.client.proxy.SearchByTitle")
    @ResponseWrapper(localName = "searchByTitleResponse", targetNamespace = "http://interfaces.server.com/", className = "com.client.proxy.SearchByTitleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.client.proxy.Song> searchByTitle(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchByAuthor", targetNamespace = "http://interfaces.server.com/", className = "com.client.proxy.SearchByAuthor")
    @ResponseWrapper(localName = "searchByAuthorResponse", targetNamespace = "http://interfaces.server.com/", className = "com.client.proxy.SearchByAuthorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.client.proxy.Song> searchByAuthor(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
